-- Execute este script no SQL Editor do Supabase para criar as tabelas necessárias

-- 1. Criar tabela de lançamentos
CREATE TABLE IF NOT EXISTS lancamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  cliente TEXT NOT NULL,
  responsaveis TEXT NOT NULL
);

-- 2. Criar tabela de itens de saída
CREATE TABLE IF NOT EXISTS itens_saida (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lancamento_id BIGINT REFERENCES lancamentos(id) ON DELETE CASCADE NOT NULL,
  produto TEXT NOT NULL,
  sku TEXT NOT NULL,
  quantidade INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pendente',
  nf_numero TEXT,
  data_status DATE,
  foto_url TEXT
);

-- 3. Configurar o Storage para as fotos
-- Crie um bucket chamado 'fotos-estoque' se não existir
INSERT INTO storage.buckets (id, name, public) 
VALUES ('fotos-estoque', 'fotos-estoque', true)
ON CONFLICT (id) DO NOTHING;

-- 4. Criar políticas de segurança (RLS) para o bucket de fotos
-- Permitir acesso público de leitura
CREATE POLICY "Fotos públicas" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'fotos-estoque');

-- Permitir upload autenticado (ou anônimo dependendo da sua configuração)
-- Para este exemplo, permitindo upload anônimo (cuidado em produção)
CREATE POLICY "Upload de fotos" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'fotos-estoque');

-- 5. Opcional: Desabilitar RLS nas tabelas para facilitar o desenvolvimento inicial
-- Em produção, você deve habilitar RLS e criar políticas adequadas
ALTER TABLE lancamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE itens_saida DISABLE ROW LEVEL SECURITY;
